name: Docs

on:
  push:
    paths:
      - packages/docs/**
    branches:
      - master

jobs:
  default:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout "${GITHUB_REF:11}" --
          git remote rm origin
          git remote add origin "https://$GH_TOKEN@github.com/intuit/proof.git"
          git fetch origin
          git branch --set-upstream-to origin/master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install
        run: |
          yarn install --frozen-lockfile
          git config --global user.email "adam@dierkens.com"
          git config --global user.name "Adam Dierkens"
      - name: Docs
        run: |
          yarn lerna run deploy --scope @proof-ui/docs --stream
